### RUST_LOG=debug cargo run

###

GET http://localhost:3000/ HTTP/1.1

###

POST http://localhost:3000 HTTP/1.1

### todos_index
GET http://localhost:3000/todos HTTP/1.1

### todos_create
POST http://localhost:3000/todos HTTP/1.1
content-type: application/json

{
    "title": "2nd todo"
}

### todos_update -1
PATCH http://localhost:3000/todos/2 HTTP/1.1
content-type: application/json

{
    "title": "第三次记录"
}

### todos_update -2
PATCH http://localhost:3000/todos/2 HTTP/1.1
content-type: application/json

{
    "completed": true
}

### todos_update -3
PATCH http://localhost:3000/todos/8 HTTP/1.1
content-type: application/json

{
    "title": "今天回来了先看电视",
    "completed": true
}

### todos_delete
DELETE http://localhost:3000/todos/9 HTTP/1.1
